version: '3'

services:
  nats:
    build:
      context: "../../nats"
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    hostname: nats-server
  api:
    build: ../../api-gateway
    ports:
        - "5000:5000"
    environment:
       NATS_URL: nats://nats:4222
       NATS_USER: ruser
       NATS_PW: T0pS3cr3t
    volumes:
        - ./test:/home/app/test
  ping:
    build: ../../ping-service
    environment:
       NATS_URL: nats://nats:4222
       NATS_USER: ruser
       NATS_PW: T0pS3cr3t
    volumes:
        - ./test:/home/app/test