version: '3'

networks:
  trifacta:
    driver: overlay

services:
  nats:
    image: vforv/hemera-nats
    networks:
        - trifacta
    ports:
        - "4222:4222"
        - "8222:8222"
    hostname: nats-server
  api:
    image: vforv/hemera-api
    ports:
        - "5000:5000"
    networks:
        - trifacta
    environment:
       NATS_URL: nats://nats:4222
       NATS_USER: ruser
       NATS_PW: T0pS3cr3t
  ping:
    image: vforv/hemera-ping
    networks:
        - trifacta
    environment:
       NATS_URL: nats://nats:4222
       NATS_USER: ruser
       NATS_PW: T0pS3cr3t
  