version: '3'
services:
  api:
    build: ../../api-gateway
    ports:
        - "5000:5000"
    environment:
       HOST: api
       BASES: bases
    volumes:
        - ./test:/home/app/test
    command: bash -c "cd api-gateway && npm test"
  ping:
    build: ../../ping-service
    environment:
       HOST: ping
       BASES: bases
    volumes:
        - ./test:/home/app/test
    command: bash -c "cd ping-service && npm test"