version: '3'

networks:
  trifacta:
    driver: overlay

services:
  consul:
    image: sdelrio/consul
    ports:
        - "8500:8500"
    networks:
        - trifacta
    environment:
      CONSUL_BIND_INTERFACE:  bases
      CONSUL: bases
    deploy:
        replicas: 1
  bases:
    image: vforv/bases:v2
    networks:
        - trifacta
    environment:
      HOST: bases
      REGISTRY: consul
    command: bash -c "cd bases-service && npm start"
  api:
    image: vforv/api-gateway:v2
    ports:
        - "5000:5000"
    networks:
        - trifacta
    environment:
      HOST:  api
      BASES: bases
      REGISTRY: consul
    command: bash -c "cd api-gateway && npm start"
  ping:
    image: vforv/ping-service:v2
    networks:
        - trifacta
    environment:
      HOST:  @eth0
      BASES: bases
      REGISTRY: consul
    command: bash -c "cd ping-service && npm start"
  